@echo off
title Installation magique
echo.
echo Downloading first part...
echo Téléchargement du premier morceau...
curl -Lo transcript_app.zip.001 "https://github.com/matahina/transcripts-made-easy/releases/latest/download/transcript_app.zip.001"
echo.
echo Downloading second part...
echo Téléchargement du deuxième morceau...
curl -Lo transcript_app.zip.002 "https://github.com/matahina/transcripts-made-easy/releases/latest/download/transcript_app.zip.002"
echo.
echo Merging parts in one big file...
echo Reconstitution des morceaux en un seul fichier...
copy /b "transcript_app.zip.*" "transcript_app_merged.zip"
echo.
echo Deleting parts...
echo Suppression des morceaux...
del transcript_app.zip.001
del transcript_app.zip.002
echo.
echo Extracting...
echo Extraction...
mkdir transcript_app
tar -xf transcript_app_merged.zip -C transcript_app
echo.
echo Deleting big archive file...
echo Suppression du gros zip...
del transcript_app_merged.zip
echo.
echo Done...
echo Fini!
pause
REM (goto) 2>nul & del "%~f0"
