name: Publication des Releases PyInstaller

# Le build se déclenche UNIQUEMENT lorsque vous poussez un tag qui commence par "v" (ex: v1.0, v2.1.4)
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    # Autorise le script à créer et modifier des Releases sur votre dépôt
    permissions:
      contents: write


    strategy:
      matrix:
        script_info: [
          {
            file: "transcript_cli.py",
            name: "transcript_cli",
            extra_args: '--exclude-module matplotlib --exclude-module PyQt5 --exclude-module tkinter --collect-all transformers --copy-metadata torchcodec --copy-metadata torch --add-data "vocabulary.txt;." --add-data "toxen.txt;."'
          },
          {
            file: "transcript_gui.py",
            name: "transcript_gui",
            extra_args: '--exclude-module matplotlib --exclude-module PyQt5 --collect-all transformers --copy-metadata torchcodec --copy-metadata torch --windowed --add-data "vocabulary.txt;." --add-data "toxen.txt;."'
          }
        ]

    steps:
    # 1. Récupérer le code source
    - name: Checkout du code
      uses: actions/checkout@v4

    # 2. Configurer Python
    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14' # Modifiez selon vos besoins

    # 3. Installer les dépendances
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install torch torchcodec --index-url https://download.pytorch.org/whl/cu126
        pip install transformers accelerate librosa content-types nagisa soynlp openai-whisper faster-whisper hf-xet
        # décommentez la ligne suivante si vous avez un fichier requirements.txt
        # pip install -r requirements.txt

    # 4. Générer l'application avec vos arguments spécifiques
    - name: Compiler ${{ matrix.script_info.name }} avec PyInstaller
      run: |
        pyinstaller --name=${{ matrix.script_info.name }} ${{ matrix.script_info.extra_args }} ${{ matrix.script_info.file }}

    # 5. Compresser le dossier généré contenant le dossier _internal
    - name: Créer l'archive ZIP
      run: |
        Compress-Archive -Path dist/${{ matrix.script_info.name }}/* -DestinationPath dist/${{ matrix.script_info.name }}.zip

    # 6. Publier le fichier ZIP directement dans la Release GitHub
    - name: Publier sur la Release GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: dist/${{ matrix.script_info.name }}.zip
