name: Publication des Releases PyInstaller

# Le build se déclenche UNIQUEMENT lorsque vous poussez un tag qui commence par "v" (ex: v1.0, v2.1.4)
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    # Autorise le script à créer et modifier des Releases sur votre dépôt
    permissions:
      contents: write

    steps:
    # 1. Récupérer le code source
    - name: Checkout du code
      uses: actions/checkout@v4

    # 2. Configurer Python
    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14' # Modifiez selon vos besoins

    # 3. Installer les dépendances
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install torch torchcodec --index-url https://download.pytorch.org/whl/cu126
        pip install transformers accelerate librosa content-types nagisa soynlp openai-whisper faster-whisper hf-xet
        # décommentez la ligne suivante si vous avez un fichier requirements.txt
        # pip install -r requirements.txt

    # - name: Debug - Lister les fichiers clonés
    #   shell: cmd
    #   run: dir /s /b

    # 4a. Générer l'application CLI
    - name: Compiler transcript_cli avec PyInstaller
      shell: cmd
      run: pyinstaller --name=transcript_cli --exclude-module matplotlib --exclude-module PyQt5 --exclude-module tkinter --collect-all transformers --copy-metadata torchcodec --copy-metadata torch --add-data "vocabulary.txt;." --add-data "token.txt;." transcript_cli.py

    # 4b. Générer l'application GUI
    - name: Compiler transcript_gui avec PyInstaller
      shell: cmd
      run: pyinstaller --name=transcript_gui --exclude-module matplotlib --exclude-module PyQt5 --collect-all transformers --copy-metadata torchcodec --copy-metadata torch --windowed --add-data "vocabulary.txt;." --add-data "token.txt;." transcript_gui.py

    # 5. Modifier l'étape 5 : Compresser les deux dossiers générés
    - name: Créer les archives ZIP
      run: |
        Compress-Archive -Path dist/transcript_cli/* -DestinationPath dist/transcript_cli.zip -CompressionLevel Optimal
        Compress-Archive -Path dist/transcript_gui/* -DestinationPath dist/transcript_gui.zip -CompressionLevel Optimal

    # 6. Modifier l'étape 6 : Publier les deux fichiers ZIP dans la Release GitHub
    - name: Publier sur la Release GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/transcript_cli.zip
          dist/transcript_gui.zip
